# Generated by Django 4.1.7 on 2023-04-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_profile_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
